"""QA-B-207d: generate clahe_bin_vectors.inc -- (vmin, vmax, v, exact bin) rows for test_clahe_bin.cpp.

The bin is computed with fractions.Fraction (exact rational arithmetic, no float intermediate):

    bin = floor((v - vmin) * 4095 / (vmax - vmin))

Rows are bit patterns (float32), so nothing depends on how a decimal is parsed. The pixels sit ON and NEXT TO the exact
boundaries k * (vmax - vmin) / 4095 (the float below, the nearest float, the float above), because that is where a one-bin
error shows. The extremes are drawn from every regime of the derivation in clahe_bin_internal.h: vmin == 0, vmin > 0 with the span
S = msb(vmax) + 1 - lsbexp(vmin) from 30 to 50 (the fast path is allowed up to 41), vmin < 0, tiny and subnormal values.

Run:  python gen_clahe_bin_vectors.py > clahe_bin_vectors.inc      (deterministic, seed fixed; write it with LF line ends)
"""
import struct
import sys
from fractions import Fraction

import numpy as np

rs = np.random.default_rng(20261004)


def bits(x):
    return struct.unpack('<I', struct.pack('<f', float(x)))[0]


def f32(x):
    return np.float32(x)


def lsb_exp(x):
    ef = (bits(x) >> 23) & 0xFF
    return max(ef, 1) - 150


rows = []


def add_image(lo, hi, boundaries=24, extra=8):
    lo, hi = f32(lo), f32(hi)
    if not hi > lo:
        return
    fl, fh = Fraction(float(lo)), Fraction(float(hi))
    pixels = [lo, hi]
    ks = list(rs.integers(1, 4095, size=boundaries)) + [1, 2, 4094, 2048, 1365, 4093]
    for k in ks:
        b = f32(float(fl + (fh - fl) * int(k) / 4095))
        pixels += [np.nextafter(b, f32(-np.inf)), b, np.nextafter(b, f32(np.inf))]
    pixels += [f32(float(fl + (fh - fl) * Fraction(float(f)))) for f in rs.random(extra)]
    for v in pixels:
        if not (lo <= v <= hi):
            continue
        exact = int((Fraction(float(v)) - fl) * 4095 / (fh - fl))
        rows.append((bits(lo), bits(hi), bits(v), exact))


# the codex #141 and #143 cases, first
add_image(0.0, 123.0)
add_image(2.0 ** -100, 4095.0)
# vmin == 0
for k in range(8):
    add_image(0.0, 10.0 ** rs.uniform(-40, 38))
# vmin > 0: span sweep. vmin = m * 2^e, vmax so that S = msb(vmax) + 1 - lsbexp(vmin) takes every value 30..50
for target in range(30, 51):
    for _ in range(3):
        lo = f32(rs.uniform(1.0, 2.0) * 2.0 ** int(rs.integers(-60, 60)))
        msb = target - 1 + lsb_exp(lo)
        if msb > 126:
            continue
        hi = f32(rs.uniform(1.0, 2.0) * 2.0 ** msb)
        add_image(lo, hi)
# vmin < 0
for _ in range(15):
    lo = f32(-rs.uniform(1.0, 2.0) * 2.0 ** int(rs.integers(-100, 60)))
    hi = f32(rs.uniform(1.0, 2.0) * 2.0 ** int(rs.integers(-100, 60)))
    add_image(lo, hi)
# tiny / subnormal / extreme
for _ in range(10):
    add_image(rs.integers(1, 1 << 22) * 2.0 ** -149, rs.integers(1 << 22, 1 << 23) * 2.0 ** -149)
    add_image(-rs.integers(1, 1 << 22) * 2.0 ** -149, rs.integers(1, 1 << 22) * 2.0 ** -149)
add_image(-3.0e38, 3.0e38)
add_image(1.0e-45, 3.0e38)
add_image(-1.0e-45, 3.0e38)

sys.stdout.write('// Generated by gen_clahe_bin_vectors.py (QA-B-207d) -- do not edit. {vmin bits, vmax bits, v bits, exact bin}\n')
for r in rows:
    sys.stdout.write('{0x%08Xu,0x%08Xu,0x%08Xu,%d},\n' % r)
sys.stderr.write('%d rows\n' % len(rows))
