#!/usr/bin/env python3
"""Input for VICTRE MC-GPU v1.5b: water slab, broad beam, optional grid (QA-A-99, #180).

Reuses gen_slab_input.py for the spectrum (beam.spc) and the one-voxel slab
(slab.vox, ASCII penEasy format), then writes run.in in the v1.5b layout.

Detector: ideal energy fluence (gain 0 -> "reporting pixel values as energy
fluence"), no cover, no fluorescence, interaction at the entrance
(scintillator mean free path 1e-6 cm). The detector model therefore does not
weight photons by energy; only the grid does.

Grid (Day & Dance 1983 model in v1.5b, focused at the SDD, 1-D):
  --grid-ratio R --grid-freq N [lines/cm] --strip-um D
  strip and interspace attenuation are ONE mean free path each, taken from
  MC-GPU material tables at --grid-energy-kev (see grid_tables.py for how
  that energy is chosen). Scatter and fluorescence inside the grid are not
  simulated by v1.5b.
"""
import argparse
import gzip
import math
import os
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.environ.get("WORK", "/root/mcsim")
MCGPU_MAT = os.path.join(WORK, "MCGPU", "materials")


def mfp_at(table, e_ev):
    """Total mean free path [cm] at e_ev, log-log interpolation, nominal density."""
    op = gzip.open if table.endswith(".gz") else open
    e, m = [], []
    with op(table, "rt") as f:
        for line in f:
            if line.startswith("#"):
                if "RAYLEIGH INTERACTIONS" in line:
                    break
                continue
            p = line.split()
            if len(p) >= 5:
                e.append(float(p[0]))
                m.append(float(p[4]))
    return float(math.exp(np.interp(math.log(e_ev), np.log(e), np.log(m))))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--thickness", type=float, required=True)
    ap.add_argument("--kvp", type=float, required=True)
    ap.add_argument("--al", type=float, default=2.5)
    ap.add_argument("--sdd", type=float, default=100.0)
    ap.add_argument("--air-gap", type=float, default=2.0)
    ap.add_argument("--field", type=float, default=30.0)
    ap.add_argument("--det-size", type=float, default=6.0)
    ap.add_argument("--pixels", type=int, default=30)
    ap.add_argument("--histories", type=float, default=1e8)
    ap.add_argument("--seed", type=int, default=1234567890)
    ap.add_argument("--mat-dir", default=os.path.join(WORK, "mat150"))
    ap.add_argument("--grid-ratio", type=float, default=0.0)
    ap.add_argument("--grid-freq", type=float, default=0.0)
    ap.add_argument("--strip-um", type=float, default=0.0)
    ap.add_argument("--grid-energy-kev", type=float, default=50.0)
    ap.add_argument("--strip-table", default=os.path.join(MCGPU_MAT, "Lead__5-120keV.mcgpu.gz"))
    ap.add_argument("--interspace-table", default=os.path.join(MCGPU_MAT, "Polycarbonate__5-120keV.mcgpu.gz"))
    ap.add_argument("--orientation", type=int, default=1)
    a = ap.parse_args()

    subprocess.run([sys.executable, os.path.join(HERE, "gen_slab_input.py"), "--out", a.out,
                    "--thickness", str(a.thickness), "--kvp", str(a.kvp), "--al", str(a.al),
                    "--sdd", str(a.sdd), "--air-gap", str(a.air_gap), "--field", str(a.field),
                    "--det-size", str(a.det_size), "--pixels", str(a.pixels),
                    "--histories", "%g" % a.histories, "--seed", str(a.seed),
                    "--mat-dir", a.mat_dir], check=True, stdout=subprocess.DEVNULL)
    os.remove(os.path.join(a.out, "run.in"))       # v1.3 layout; replaced below

    src_to_slab = a.sdd - a.thickness - a.air_gap
    ap_deg = 2.0 * math.degrees(math.atan(0.5 * a.field / a.sdd))
    grid_on = a.grid_ratio > 0 and a.grid_freq > 0 and a.strip_um > 0
    e_ev = a.grid_energy_kev * 1000.0
    strip_mfp = mfp_at(a.strip_table, e_ev) if grid_on else 1.0
    inter_mfp = mfp_at(a.interspace_table, e_ev) if grid_on else 1.0
    period = 1.0 / a.grid_freq if grid_on else 0.0
    height = a.grid_ratio * (period - a.strip_um * 1e-4) if grid_on else 0.0

    with open(os.path.join(a.out, "run.in"), "w") as f:
        f.write("""# VICTRE MC-GPU v1.5b input -- generated by tools/mcsim/gen_victre_input.py (QA-A-99)
# thickness=%g cm kVp=%g Al=%g mm sdd=%g cm air_gap=%g cm field=%g cm at detector
# grid: %s ratio=%g freq=%g /cm strip=%g um height=%.5f cm E_mfp=%g keV strip_mfp=%.6g cm interspace_mfp=%.6g cm
#   strip table %s ; interspace table %s
#[SECTION SIMULATION CONFIG v.2009-05-12]
%g
%d
0
128
150
#[SECTION SOURCE v.2016-12-02]
beam.spc
%g %g %g
0.0 1.0 0.0
%.6f %.6f
0.0 0.0 0.0
0.0
0.0
NO
#[SECTION IMAGE DETECTOR v.2017-06-20]
image.dat
%d %d
%g %g
%g
0.0 0.0
0.1
0.000001
1.0e9 0.0 0.0 1.0
0.0 0.0
0.0
0.0 0.0
%g %g %g
%.8g %.8g
%d
#[SECTION TOMOGRAPHIC TRAJECTORY v.2016-12-02]
1
#[SECTION DOSE DEPOSITION v.2012-12-12]
NO
NO
dose.dat
1 1
1 1
1 1
#[SECTION VOXELIZED GEOMETRY FILE v.2017-07-26]
slab.vox
0.0 0.0 0.0
0 0 0
1.0 1.0 1.0
0 0 0
#[SECTION MATERIAL FILE LIST v.2009-11-30]
%s/water.mcgpu density=1.0
%s/air.mcgpu density=0.0012
""" % (a.thickness, a.kvp, a.al, a.sdd, a.air_gap, a.field,
       "ON" if grid_on else "OFF", a.grid_ratio, a.grid_freq, a.strip_um, height,
       a.grid_energy_kev, strip_mfp, inter_mfp,
       os.path.basename(a.strip_table), os.path.basename(a.interspace_table),
       a.histories, a.seed,
       0.5 * 60.0, -src_to_slab, 0.5 * 60.0, ap_deg, ap_deg,
       a.pixels, a.pixels, a.det_size, a.det_size, a.sdd,
       (a.grid_ratio if grid_on else 0.0), (a.grid_freq if grid_on else 0.0),
       (a.strip_um * 1e-4 if grid_on else 0.0), strip_mfp, inter_mfp, a.orientation,
       a.mat_dir, a.mat_dir))
    print("grid=%s height=%.4f cm strip_mfp=%.5g cm interspace_mfp=%.5g cm at %g keV"
          % ("ON" if grid_on else "OFF", height, strip_mfp, inter_mfp, a.grid_energy_kev))


if __name__ == "__main__":
    main()
