#!/usr/bin/env python3
"""Generate an MC-GPU v1.3 run for a water slab (QA-A-94, #180).

Writes three files into --out:
  slab.vox   one-voxel water slab (penEasy 2008 voxel format)
  beam.spc   tungsten spectrum from SpekPy (lower bin edge in eV, probability)
  run.in     MC-GPU input file

Geometry (MC-GPU coordinates, cm): the slab occupies x in [0, SLAB_XZ],
y in [0, thickness], z in [0, SLAB_XZ]. The source sits on the slab axis at
y = -(sdd - thickness - air_gap) and points along +y, so the detector plane is
air_gap cm behind the slab exit face. MC-GPU transports nothing outside the
voxel box, so the air gap is vacuum.

A field of 0 gives a pencil beam (MC-GPU treats a zero aperture as a single
direction). A field W > 0 gives a W x W cm rectangle at the detector plane.
"""
import argparse
import math
import os

SLAB_XZ = 60.0  # lateral slab size, cm -- larger than any field used here


def write_spectrum(path, kvp, al_mm, anode_deg):
    import spekpy as sp
    s = sp.Spek(kvp=kvp, th=anode_deg, dk=0.5)
    if al_mm > 0:
        s.filter("Al", al_mm)
    k, phi = s.get_spectrum(edges=True)  # k: bin edges pairs (keV), phi: fluence
    # get_spectrum(edges=True) returns duplicated edge points; take lower edges.
    lows_all = k[0::2]
    probs_all = phi[0::2]
    # MC-GPU material tables start at 5 keV; bins below are dropped and the
    # dropped fluence fraction is reported.
    keep = [i for i, e in enumerate(lows_all) if e >= 5.0]
    lows = [lows_all[i] for i in keep]
    probs = [probs_all[i] for i in keep]
    dropped = 1.0 - float(sum(probs)) / float(sum(probs_all))
    total = float(sum(probs))
    with open(path, "w") as f:
        f.write("# SpekPy %s kVp=%g anode=%g deg Al=%g mm (lower bin edge eV, probability)\n"
                % (sp.__version__ if hasattr(sp, "__version__") else "?", kvp, anode_deg, al_mm))
        for e, p in zip(lows, probs):
            f.write("%.1f %.8e\n" % (e * 1000.0, p / total))
        f.write("%.1f -1\n" % (kvp * 1000.0))
    mean_kev = sum(e * p for e, p in zip(lows, probs)) / total
    return mean_kev, s.get_hvl1(), dropped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--thickness", type=float, default=20.0, help="water slab, cm")
    ap.add_argument("--kvp", type=float, default=80.0)
    ap.add_argument("--al", type=float, default=2.5, help="total Al filtration, mm")
    ap.add_argument("--anode", type=float, default=12.0, help="anode angle, deg")
    ap.add_argument("--sdd", type=float, default=100.0, help="source-detector distance, cm")
    ap.add_argument("--air-gap", type=float, default=2.0, help="slab exit face to detector, cm")
    ap.add_argument("--field", type=float, default=0.0, help="square field at detector, cm; 0 = pencil")
    ap.add_argument("--det-size", type=float, default=60.0, help="detector side, cm")
    ap.add_argument("--pixels", type=int, default=600, help="detector pixels per side")
    ap.add_argument("--histories", type=float, default=1e8)
    ap.add_argument("--seed", type=int, default=1234567890)
    ap.add_argument("--mat-dir", default="/root/mcsim/mat")
    a = ap.parse_args()

    os.makedirs(a.out, exist_ok=True)
    src_to_slab = a.sdd - a.thickness - a.air_gap
    if src_to_slab <= 0:
        raise SystemExit("sdd too small for thickness + air gap")

    with open(os.path.join(a.out, "slab.vox"), "w") as f:
        f.write("[SECTION VOXELS HEADER v.2008-04-13]\n")
        f.write("1 1 1   No. OF VOXELS IN X,Y,Z\n")
        f.write("%g %g %g   VOXEL SIZE (cm) ALONG X,Y,Z\n" % (SLAB_XZ, a.thickness, SLAB_XZ))
        f.write("1   COLUMN NUMBER WHERE MATERIAL ID IS LOCATED\n")
        f.write("2   COLUMN NUMBER WHERE THE MASS DENSITY IS LOCATED\n")
        f.write("0   BLANK LINE AFTER EACH X,Y COLUMN?\n")
        f.write("[END OF VXH SECTION]\n")
        f.write("1 1.0\n")  # material 1 = water, 1.0 g/cm^3

    mean_kev, hvl, dropped = write_spectrum(os.path.join(a.out, "beam.spc"), a.kvp, a.al, a.anode)

    ap_deg = 0.0 if a.field <= 0 else 2.0 * math.degrees(math.atan(0.5 * a.field / a.sdd))
    c = 0.5 * SLAB_XZ
    with open(os.path.join(a.out, "run.in"), "w") as f:
        f.write("""# MC-GPU v1.3 input -- generated by tools/mcsim/gen_slab_input.py
# thickness=%g cm kVp=%g Al=%g mm anode=%g deg sdd=%g cm air_gap=%g cm field=%g cm
# spectrum mean=%.3f keV HVL1=%.3f mm Al dropped_below_5keV=%.3e
#[SECTION SIMULATION CONFIG v.2009-05-12]
%g
%d
0
128
150
#[SECTION SOURCE v.2011-07-12]
beam.spc
%g %g %g
0.0 1.0 0.0
%.6f %.6f
#[SECTION IMAGE DETECTOR v.2009-12-02]
image.dat
%d %d
%g %g
%g
#[SECTION CT SCAN TRAJECTORY v.2011-10-25]
1
0.0
0.0 5000.0
%g
0.0
#[SECTION DOSE DEPOSITION v.2012-12-12]
NO
NO
dose.dat
1 1
1 1
1 1
#[SECTION VOXELIZED GEOMETRY FILE v.2009-11-30]
slab.vox
#[SECTION MATERIAL FILE LIST v.2009-11-30]
%s/water.mcgpu
%s/air.mcgpu
""" % (a.thickness, a.kvp, a.al, a.anode, a.sdd, a.air_gap, a.field, mean_kev, hvl, dropped,
       a.histories, a.seed,
       c, -src_to_slab, c, ap_deg, ap_deg,
       a.pixels, a.pixels, a.det_size, a.det_size, a.sdd,
       src_to_slab + 0.5 * a.thickness,
       a.mat_dir, a.mat_dir))
    print("wrote %s  mean=%.2f keV  HVL1=%.3f mm Al  dropped<5keV=%.3e  aperture=%.4f deg"
          % (a.out, mean_kev, hvl, dropped, ap_deg))


if __name__ == "__main__":
    main()
