if(EXISTS "D:/workspace-github/xpe-post/build_test3/modules/display/test_display_voi_lut[1]_tests.cmake")
  include("D:/workspace-github/xpe-post/build_test3/modules/display/test_display_voi_lut[1]_tests.cmake")
else()
  add_test(test_display_voi_lut_NOT_BUILT test_display_voi_lut_NOT_BUILT)
endif()
