/**
 * @file test_onnx_session.cpp
 * @brief The ONNX Runtime inference path, end to end (QA-B-160, #130).
 *
 * REQ-AI-006: ONNX Runtime 1.20+ integration.
 *
 * WHAT THESE TESTS ARE FOR. Until QA-B-160 this module linked no ONNX Runtime
 * at all, and 156 "ai tests" were green while asserting nothing about
 * inference (#205, QA-B-154). So the load-bearing test here is not "a session
 * can be created" -- a stub passes that -- it is
 * RunningADifferentModelChangesTheOutput: two models that differ ONLY in a
 * scale constant must produce different numbers from the same input. This
 * repository has twice shipped a model that was computed and executed and then
 * cancelled out of the answer (#154, #155); an echo, a no-op, or a stub cannot
 * pass that assertion.
 *
 * THE MODELS are generated by tests/data/make_min_models.py with no onnx
 * package -- a hand-written protobuf, 116 bytes each: Y = X * 2 and Y = X * 3,
 * float32 [4]. They are committed because regenerating them needs nothing but
 * python, and a test that silently skips when its fixture is missing is the
 * shape #205 was about.
 *
 * IN A STUB BUILD five of these tests SKIP -- there is no model to load, so
 * there is nothing for them to assert. Four still run and pin the stub's own
 * contract (Run returns kModelLoadFailed and does NOT echo the input; a missing
 * file is still kInvalidModelPath; CPU is the only provider offered).
 *
 * A skip counts as a pass in ctest, which is how a green job can mean nothing
 * (#205). AFullBuildIsProvableWhenTheCallerSaysItExpectedOne exists for that:
 * a job that is supposed to link ONNX sets XPE_AI_EXPECT_ONNX=1 and the skip
 * becomes a red. Measured both ways -- stub+claim fails, full+claim passes,
 * stub without the claim stays green.
 */

#include <gtest/gtest.h>

#include "xpe/ai/ai_onnx_session.h"

#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

using xpe::ai::OnnxSession;
using xpe::ai::OnnxSessionConfig;
using xpe::ai::OnnxErrorCode;
using xpe::ai::ExecutionProvider;

namespace {

// gtest_discover_tests sets WORKING_DIRECTORY to modules/ai (CMakeLists).
const char* kScale2 = "tests/data/min_scale2.onnx";
const char* kScale3 = "tests/data/min_scale3.onnx";
const char* kGarbage = "tests/data/not_a_model.onnx";

bool Exists(const char* p) {
    std::ifstream f(p, std::ios::binary);
    return f.good();
}

OnnxSessionConfig Cfg(const char* path) {
    OnnxSessionConfig c;
    c.model_path = path;
    c.execution_provider = ExecutionProvider::kCpu;
    c.num_threads = 1;
    return c;
}

}  // namespace

// --- the fixtures must be there, or every test below means nothing ---------

TEST(OnnxSessionFixtures, ModelFilesArePresent) {
    EXPECT_TRUE(Exists(kScale2)) << kScale2
        << " is missing; regenerate with tests/data/make_min_models.py";
    EXPECT_TRUE(Exists(kScale3)) << kScale3;
    EXPECT_TRUE(Exists(kGarbage)) << kGarbage;
}

// --- stub vs full: the two contracts, stated separately --------------------

TEST(OnnxSessionRun, StubBuildRefusesToRunAndDoesNotEcho) {
    if (!OnnxSession::IsStubBuild()) {
        GTEST_SKIP() << "full build: the stub contract does not apply. The full "
                        "behaviour is asserted by RunningADifferentModelChangesTheOutput.";
    }
    auto s = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s.has_value()) << s.message;

    const std::vector<float> x{1.0f, 2.0f, 3.0f, 4.0f};
    auto r = s.value->Run(x);
    EXPECT_EQ(OnnxErrorCode::kModelLoadFailed, r.code)
        << "a stub build has no model; returning kOk here would let a stub read "
           "as a working inference path (#205)";
    EXPECT_TRUE(r.value.empty()) << "the stub must not echo the input back";
}

// --- THE falsification: does the model actually decide the answer? ---------

TEST(OnnxSessionRun, RunningADifferentModelChangesTheOutput) {
    if (OnnxSession::IsStubBuild()) {
        GTEST_SKIP() << "stub build: no ONNX Runtime linked, so there is no model "
                        "to swap. Build with -DXPE_AI_USE_ONNXRUNTIME=ON "
                        "-DXPE_AI_STUB_BUILD=OFF -DONNXRUNTIME_ROOT=<dir>. "
                        "This skip is the #205 hazard in miniature: if no CI job "
                        "ever takes the full branch, this assertion never runs.";
    }
    const std::vector<float> x{1.0f, 2.0f, 3.0f, 4.0f};

    auto s2 = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s2.has_value()) << s2.message;
    auto y2 = s2.value->Run(x);
    ASSERT_EQ(OnnxErrorCode::kOk, y2.code) << y2.message;

    auto s3 = OnnxSession::Create(Cfg(kScale3));
    ASSERT_TRUE(s3.has_value()) << s3.message;
    auto y3 = s3.value->Run(x);
    ASSERT_EQ(OnnxErrorCode::kOk, y3.code) << y3.message;

    ASSERT_EQ(x.size(), y2.value.size());
    ASSERT_EQ(x.size(), y3.value.size());

    // The numbers, not just "they differ": x*2 and x*3.
    for (size_t i = 0; i < x.size(); ++i) {
        EXPECT_FLOAT_EQ(x[i] * 2.0f, y2.value[i]) << "i=" << i;
        EXPECT_FLOAT_EQ(x[i] * 3.0f, y3.value[i]) << "i=" << i;
    }

    // And the pair differs, which no echo or no-op can satisfy.
    bool anyDifferent = false;
    for (size_t i = 0; i < x.size(); ++i)
        if (y2.value[i] != y3.value[i]) anyDifferent = true;
    EXPECT_TRUE(anyDifferent)
        << "the two models gave identical output -- the model is not deciding "
           "the answer, which is exactly the defect #154/#155 recorded";

    // Control: the input itself is not what came back.
    EXPECT_NE(x, y2.value) << "output equals input -- this is an echo, not inference";
}

TEST(OnnxSessionRun, OutputIsNotAConstantIndependentOfInput) {
    if (OnnxSession::IsStubBuild()) GTEST_SKIP() << "stub build";
    auto s = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s.has_value()) << s.message;

    auto a = s.value->Run({1.0f, 1.0f, 1.0f, 1.0f});
    auto b = s.value->Run({5.0f, 6.0f, 7.0f, 8.0f});
    ASSERT_EQ(OnnxErrorCode::kOk, a.code) << a.message;
    ASSERT_EQ(OnnxErrorCode::kOk, b.code) << b.message;
    EXPECT_NE(a.value, b.value)
        << "the same session returned the same values for different inputs";
}

// --- failure paths reach the caller as codes, not as crashes or as kOk -----

TEST(OnnxSessionCreate, MissingModelIsInvalidModelPath) {
    auto s = OnnxSession::Create(Cfg("tests/data/there_is_no_such_model.onnx"));
    EXPECT_FALSE(s.has_value());
    EXPECT_EQ(OnnxErrorCode::kInvalidModelPath, s.code) << s.message;
    EXPECT_EQ(nullptr, s.value);
}

TEST(OnnxSessionCreate, GarbageFileIsModelLoadFailed) {
    if (OnnxSession::IsStubBuild()) {
        GTEST_SKIP() << "stub build: nothing parses the file, so a stub accepts "
                        "garbage. That is itself why the stub must not be read "
                        "as verifying model loading.";
    }
    auto s = OnnxSession::Create(Cfg(kGarbage));
    EXPECT_FALSE(s.has_value());
    EXPECT_EQ(OnnxErrorCode::kModelLoadFailed, s.code) << s.message;
    EXPECT_EQ(nullptr, s.value) << "a session that failed to load must not be handed back";
    EXPECT_FALSE(s.message.empty()) << "the failure must say something a caller can act on";
}

TEST(OnnxSessionRun, WrongInputLengthIsInvalidInput) {
    if (OnnxSession::IsStubBuild()) GTEST_SKIP() << "stub build";
    auto s = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s.has_value()) << s.message;

    auto r = s.value->Run({1.0f, 2.0f});          // model declares 4
    EXPECT_EQ(OnnxErrorCode::kInvalidInput, r.code) << r.message;
    EXPECT_TRUE(r.value.empty());
}

TEST(OnnxSessionRun, EmptyInputIsInvalidInput) {
    auto s = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s.has_value()) << s.message;
    auto r = s.value->Run({});
    EXPECT_EQ(OnnxErrorCode::kInvalidInput, r.code) << r.message;
}

// --- metadata read off the real graph --------------------------------------

TEST(OnnxSessionMetadata, InputAndOutputAreReadFromTheModel) {
    if (OnnxSession::IsStubBuild()) {
        GTEST_SKIP() << "stub build: metadata lists are empty by contract";
    }
    auto s = OnnxSession::Create(Cfg(kScale2));
    ASSERT_TRUE(s.has_value()) << s.message;

    const auto in = s.value->GetInputMetadata();
    const auto out = s.value->GetOutputMetadata();
    ASSERT_EQ(1u, in.size());
    ASSERT_EQ(1u, out.size());
    EXPECT_EQ("X", in.front().name) << "the name comes from the graph, not from a constant";
    EXPECT_EQ("Y", out.front().name);
    ASSERT_EQ(1u, in.front().shape.size());
    EXPECT_EQ(4, in.front().shape.front());
}

// --- the skip itself has to be catchable -----------------------------------

TEST(OnnxSessionBuildMode, AFullBuildIsProvableWhenTheCallerSaysItExpectedOne) {
    // Five tests above SKIP in a stub build. ctest counts a skip as a pass, so
    // a job that builds the stub goes green while the load-bearing assertion
    // never executes -- the #205 shape, one level in. There is no way for the
    // test to know whether the skip was intended, so the CALLER declares it:
    // set XPE_AI_EXPECT_ONNX=1 in the job that is supposed to link ONNX, and
    // this test turns a silent skip into a red.
    //
    // Unset (developers, and any job that deliberately builds the stub) it
    // asserts nothing, so it cannot make a legitimate stub build fail.
#ifdef _MSC_VER
    size_t len = 0;
    char buf[8] = {0};
    const bool present = (getenv_s(&len, buf, sizeof(buf), "XPE_AI_EXPECT_ONNX") == 0) && len > 1;
    const std::string want = present ? std::string(buf) : std::string();
#else
    const char* raw = std::getenv("XPE_AI_EXPECT_ONNX");
    const std::string want = raw ? raw : std::string();
#endif
    if (want.empty() || want == "0") {
        GTEST_SKIP() << "XPE_AI_EXPECT_ONNX is not set, so no claim is being made "
                        "about which build this is. A CI job that links ONNX should "
                        "set it to 1 -- otherwise its skips are indistinguishable "
                        "from a stub build that silently lost the runtime.";
    }
    EXPECT_FALSE(OnnxSession::IsStubBuild())
        << "XPE_AI_EXPECT_ONNX=" << want << " says this build links ONNX Runtime, "
           "but it is a stub build. The inference tests above are skipping, and "
           "this job is green for that reason alone.";
}

TEST(OnnxSessionProviders, CpuIsReportedAndTheListComesFromTheRuntime) {
    const auto eps = OnnxSession::GetAvailableExecutionProviders();
    ASSERT_FALSE(eps.empty());
    EXPECT_EQ(ExecutionProvider::kCpu, eps.front()) << "CPU is always available";

    if (OnnxSession::IsStubBuild()) {
        EXPECT_EQ(1u, eps.size()) << "a stub build can only offer CPU";
    } else {
        // Not "CUDA is present" -- that depends on the machine. What is
        // asserted is that the list no longer names providers unconditionally:
        // before QA-B-160 this returned CPU+CUDA+TensorRT+DirectML on every
        // build, including a CPU-only package like the one CI uses.
        EXPECT_LE(eps.size(), 4u);
    }
}
