add_test([=[VoiLut.Linear_CenterWindow]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Linear_CenterWindow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Linear_CenterWindow]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Linear_ClampMin]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Linear_ClampMin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Linear_ClampMin]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Linear_ClampMax]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Linear_ClampMax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Linear_ClampMax]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.LinearExact_CenterValue]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.LinearExact_CenterValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.LinearExact_CenterValue]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Sigmoid_CenterValue]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Sigmoid_CenterValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Sigmoid_CenterValue]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Sigmoid_OutputClampedToRange]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Sigmoid_OutputClampedToRange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Sigmoid_OutputClampedToRange]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Error_NullImg]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Error_NullImg]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Error_NullImg]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Error_NullParams]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Error_NullParams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Error_NullParams]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Error_WrongFormat]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Error_WrongFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Error_WrongFormat]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Error_ZeroWidth]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Error_ZeroWidth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Error_ZeroWidth]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Error_NegativeWidth]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Error_NegativeWidth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Error_NegativeWidth]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_Bone]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_Bone]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_Bone]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_Lung]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_Lung]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_Lung]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_Abdomen]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_Abdomen]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_Abdomen]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_Head]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_Head]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_Head]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_InvalidBodyPart]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_InvalidBodyPart]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_InvalidBodyPart]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Preset_NullParams]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Preset_NullParams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Preset_NullParams]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VoiLut.Performance_3072x3072]=]  D:/workspace-github/xpe-post/build_test2/bin/test_display_voi_lut.exe [==[--gtest_filter=VoiLut.Performance_3072x3072]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VoiLut.Performance_3072x3072]=]  PROPERTIES WORKING_DIRECTORY D:/workspace-github/xpe-post/modules/display SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_display_voi_lut_TESTS VoiLut.Linear_CenterWindow VoiLut.Linear_ClampMin VoiLut.Linear_ClampMax VoiLut.LinearExact_CenterValue VoiLut.Sigmoid_CenterValue VoiLut.Sigmoid_OutputClampedToRange VoiLut.Error_NullImg VoiLut.Error_NullParams VoiLut.Error_WrongFormat VoiLut.Error_ZeroWidth VoiLut.Error_NegativeWidth VoiLut.Preset_Bone VoiLut.Preset_Lung VoiLut.Preset_Abdomen VoiLut.Preset_Head VoiLut.Preset_InvalidBodyPart VoiLut.Preset_NullParams VoiLut.Performance_3072x3072)
