using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text.RegularExpressions;

namespace ImageProcTest
{
    /// <summary>
    /// The runtime smoke of xpe_preprocess.dll behind "Synthetic oracle ready": a 16x16 offset -> gain -> defect chain, run twice, against the DLL on THIS machine.
    ///
    /// GUI-C-212 (#249): this used to call the correction functions as (image, map[, config]) -- a shape the header never had (xpe_offset_correct takes
    /// (input, output, metadata) since 2026-04-16) -- and never loaded a calibration. It passed by accident until 2026-09-10 (when the module began to answer
    /// XPE_ERR_CALIB_NOT_LOADED for an uncalibrated call), then failed for the right reason of the wrong call, and "NaN/Inf 0, RMSE 0" were zeros of an output nothing had written.
    /// Now the chain is the module's contract (calibration state model, #117): offset and gain maps are GENERATED by the module from synthetic dark and flat frames into a
    /// temporary folder and LOADED, a defect map (an XCal file, written here -- the module has no generator for one) is loaded, and each stage must return OK and must have an
    /// effect; the verdict requires non-zero output, so a chain that wrote nothing cannot pass.
    ///
    /// GUI-C-212b (#249, Codex #96): this class runs in its OWN PROCESS (<see cref="XpePreprocessOracleProcess"/>). It calls xpe_preprocess_shutdown, loads synthetic maps into the module's
    /// process-global calibration store and shuts down again, which in the app's process would erase whatever calibration the operator had loaded and let a concurrent call see the
    /// synthetic maps. Restoring the state in-process was rejected: there is no way to guarantee a complete restore of global state. The worker owns its temporary folder: a deletion
    /// failure is reported in <see cref="PreprocessSyntheticOracleResult.TempCleanupWarning"/>, and a start reclaims this class's own folders that are older than <see cref="DefaultStaleAge"/>.
    ///
    /// Guarded by IntegrationTests (OracleCallTests): a diagnostic nobody tests rots, and this one did for months.
    /// </summary>
    internal static class XpePreprocessSyntheticOracle
    {
        private const int Width = 16;
        private const int Height = 16;
        private const int PixelCount = Width * Height;
        private const ushort HotValue = 60000;
        private const float HotEffect = 50000f;

        /// <summary>A folder of this class older than this was left by a run that did not finish; a younger one may belong to a run still going and is never touched.</summary>
        public static readonly TimeSpan DefaultStaleAge = TimeSpan.FromHours(1);

        private static readonly Regex OwnFolder = new("^xpe_oracle_[0-9a-f]{32}$", RegexOptions.Compiled);

        /// <summary>Test seams: where the temporary folders live, a hook called once the run's folder exists, and the age beyond which an old folder is reclaimed.</summary>
        public sealed record OracleOptions(string? TempRoot = null, Action<string>? OnTempDirReady = null, TimeSpan? StaleAge = null);

        // Two isolated pixels the defect map marks; the input carries a hot value there, so a defect stage that does nothing is visible.
        private static readonly int[] DefectPixels = [5 * Width + 5, 12 * Width + 9];

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate XpeCommonApi.XpeErrorCode InitDelegate(IntPtr config);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void ShutdownDelegate();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate XpeCommonApi.XpeErrorCode CorrectionDelegate(
            ref XpeCommonApi.XpeImageBuffer input,
            ref XpeCommonApi.XpeImageBuffer output,
            ref XpeCommonApi.XpeImageMetadata metadata);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        private delegate XpeCommonApi.XpeErrorCode GenerateOffsetDelegate(
            [In] XpeCommonApi.XpeImageBuffer[] darkFrames,
            int numFrames,
            float integrationTimeMs,
            float temperatureC,
            [MarshalAs(UnmanagedType.LPStr)] string outputPath,
            [MarshalAs(UnmanagedType.LPStr)] string? configJsonOrNull);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        private delegate XpeCommonApi.XpeErrorCode GenerateGainDelegate(
            [In] XpeCommonApi.XpeImageBuffer[] flatFrames,
            int numFrames,
            IntPtr darkReferenceOrNull,
            [MarshalAs(UnmanagedType.LPStr)] string outputPath,
            [MarshalAs(UnmanagedType.LPStr)] string? metadataJsonOrNull);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        private delegate XpeCommonApi.XpeErrorCode LoadDelegate([MarshalAs(UnmanagedType.LPStr)] string path);

        private sealed record Exports(
            InitDelegate Init,
            ShutdownDelegate Shutdown,
            CorrectionDelegate Offset,
            CorrectionDelegate Gain,
            CorrectionDelegate Defect,
            GenerateOffsetDelegate GenerateOffset,
            GenerateGainDelegate GenerateGain,
            LoadDelegate LoadOffset,
            LoadDelegate LoadGain,
            LoadDelegate LoadDefect);

        public static PreprocessSyntheticOracleResult Run(string dllPath, OracleOptions? options = null)
        {
            if (!File.Exists(dllPath))
            {
                return PreprocessSyntheticOracleResult.NotRun($"DLL not found: {dllPath}");
            }

            NativeDependencyLoader.TryLoadFor(dllPath);
            if (!NativeLibrary.TryLoad(dllPath, out var handle))
            {
                return PreprocessSyntheticOracleResult.NotRun($"DLL load failed: {dllPath}");
            }

            var warnings = new List<string>();
            string? tempDir = null;
            Exports? exports = null;
            PreprocessSyntheticOracleResult result;
            try
            {
                var root = options?.TempRoot ?? Path.GetTempPath();
                ReclaimStaleFolders(root, options?.StaleAge ?? DefaultStaleAge, warnings);
                tempDir = Path.Combine(root, $"xpe_oracle_{Guid.NewGuid():N}");
                exports = Bind(handle);
                result = exports is null
                    ? PreprocessSyntheticOracleResult.NotRun("Mandatory correction or calibration exports are not available.")
                    : RunWith(exports, tempDir, options);
            }
            catch (Exception ex)
            {
                result = Failed("Synthetic oracle exception", ex.Message);
            }
            finally
            {
                try
                {
                    exports?.Shutdown();
                }
                catch (Exception)
                {
                    // The DLL is about to be released; a shutdown failure here has no one to tell.
                }

                NativeLibrary.Free(handle);
                if (tempDir is not null)
                {
                    try
                    {
                        if (Directory.Exists(tempDir))
                        {
                            Directory.Delete(tempDir, recursive: true);
                        }
                    }
                    catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                    {
                        warnings.Add($"temporary folder {tempDir} was not deleted: {ex.Message}");
                    }
                }
            }

            return warnings.Count == 0 ? result : result with { TempCleanupWarning = string.Join(" | ", warnings) };
        }

        /// <summary>Removes this class's own folders (exact name shape) under <paramref name="root"/> that are older than <paramref name="age"/>; whatever cannot be removed is reported.</summary>
        private static void ReclaimStaleFolders(string root, TimeSpan age, List<string> warnings)
        {
            if (!Directory.Exists(root))
            {
                return;
            }

            foreach (var dir in Directory.EnumerateDirectories(root))
            {
                if (!OwnFolder.IsMatch(Path.GetFileName(dir)) || DateTime.UtcNow - Directory.GetLastWriteTimeUtc(dir) <= age)
                {
                    continue;
                }

                try
                {
                    Directory.Delete(dir, recursive: true);
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    warnings.Add($"stale folder {dir} was not reclaimed: {ex.Message}");
                }
            }
        }

        private static PreprocessSyntheticOracleResult RunWith(Exports exports, string tempDir, OracleOptions? options)
        {
            exports.Shutdown();
            var initResult = exports.Init(IntPtr.Zero);
            if (initResult != XpeCommonApi.XpeErrorCode.OK)
            {
                return Failed("Init failed", $"xpe_preprocess_init(NULL) returned {initResult}.");
            }

            Directory.CreateDirectory(tempDir);
            options?.OnTempDirReady?.Invoke(tempDir);
            var setup = LoadCalibration(exports, tempDir);
            if (setup is not null)
            {
                return Failed("Calibration setup failed", setup);
            }

            var first = RunChain(exports);
            var second = RunChain(exports);
            var determinismRmse = CalculateRmse(first.Output, second.Output);
            var outputSha = ComputeSha256(first.Output);
            var passed = first.Passed && second.Passed && determinismRmse == 0;

            return new PreprocessSyntheticOracleResult(
                Status: passed ? "Synthetic oracle pass" : "Synthetic oracle fail",
                Details: passed
                    ? "16x16 synthetic offset->gain->defect adapter chain passed with generated and loaded calibration."
                    : "Synthetic adapter chain executed but one or more gates failed.",
                Executed: true,
                Passed: passed,
                TotalLatencyMs: first.TotalLatencyMs + second.TotalLatencyMs,
                InputPreserved: first.InputPreserved && second.InputPreserved,
                RawSha256Before: first.RawSha256Before,
                RawSha256After: first.RawSha256After,
                OutputSha256: outputSha,
                NaNInfCount: first.NaNInfCount + second.NaNInfCount,
                DeterminismRmse: determinismRmse,
                OutputMin: first.OutputMin,
                OutputMax: first.OutputMax,
                Stages: first.Stages);
        }

        private static PreprocessSyntheticOracleResult Failed(string status, string details) => PreprocessSyntheticOracleResult.Failed(status, details);

        private static Exports? Bind(IntPtr handle)
        {
            if (!TryGetDelegate(handle, "xpe_preprocess_init", out InitDelegate? init) ||
                !TryGetDelegate(handle, "xpe_preprocess_shutdown", out ShutdownDelegate? shutdown) ||
                !TryGetDelegate(handle, "xpe_offset_correct", out CorrectionDelegate? offset) ||
                !TryGetDelegate(handle, "xpe_gain_correct", out CorrectionDelegate? gain) ||
                !TryGetDelegate(handle, "xpe_defect_correct", out CorrectionDelegate? defect) ||
                !TryGetDelegate(handle, "xpe_calib_generate_offset", out GenerateOffsetDelegate? generateOffset) ||
                !TryGetDelegate(handle, "xpe_calib_generate_gain", out GenerateGainDelegate? generateGain) ||
                !TryGetDelegate(handle, "xpe_calib_load_offset", out LoadDelegate? loadOffset) ||
                !TryGetDelegate(handle, "xpe_calib_load_gain", out LoadDelegate? loadGain) ||
                !TryGetDelegate(handle, "xpe_calib_load_defect_map", out LoadDelegate? loadDefect))
            {
                return null;
            }

            return new Exports(init!, shutdown!, offset!, gain!, defect!, generateOffset!, generateGain!, loadOffset!, loadGain!, loadDefect!);
        }

        /// <summary>Generates the offset and gain maps with the module, writes the defect map, and loads all three. Returns null on success, otherwise the first failure.</summary>
        private static string? LoadCalibration(Exports e, string tempDir)
        {
            var offsetPath = Path.Combine(tempDir, "offset.xcal");
            var gainPath = Path.Combine(tempDir, "gain.xcal");
            var defectPath = Path.Combine(tempDir, "defect.xcal");

            // Dark frame: a flat low pedestal. Flat frame: a brighter field that VARIES per pixel -- a uniform flat gives a gain map of all ones, and a gain stage that did nothing
            // would then be indistinguishable from one that worked.
            var dark = Enumerable.Repeat((ushort)100, PixelCount).ToArray();
            var flat = FlatFrame();
            var darkPin = GCHandle.Alloc(dark, GCHandleType.Pinned);
            var flatPin = GCHandle.Alloc(flat, GCHandleType.Pinned);
            try
            {
                var darkFrame = MakeBuffer(XpeCommonApi.XpePixelFormat.UInt16, darkPin.AddrOfPinnedObject(), dark.Length * sizeof(ushort));
                var flatFrame = MakeBuffer(XpeCommonApi.XpePixelFormat.UInt16, flatPin.AddrOfPinnedObject(), flat.Length * sizeof(ushort));

                var step = e.GenerateOffset([darkFrame], 1, 100.0f, 25.0f, offsetPath, null);
                if (step != XpeCommonApi.XpeErrorCode.OK) return $"xpe_calib_generate_offset returned {step}.";
                step = e.LoadOffset(offsetPath);
                if (step != XpeCommonApi.XpeErrorCode.OK) return $"xpe_calib_load_offset returned {step}.";

                step = e.GenerateGain([flatFrame], 1, IntPtr.Zero, gainPath, null);
                if (step != XpeCommonApi.XpeErrorCode.OK) return $"xpe_calib_generate_gain returned {step}.";
                step = e.LoadGain(gainPath);
                if (step != XpeCommonApi.XpeErrorCode.OK) return $"xpe_calib_load_gain returned {step}.";
            }
            finally
            {
                flatPin.Free();
                darkPin.Free();
            }

            WriteDefectMapFile(defectPath);
            var load = e.LoadDefect(defectPath);
            return load == XpeCommonApi.XpeErrorCode.OK ? null : $"xpe_calib_load_defect_map returned {load}.";
        }

        /// <summary>
        /// A DEFECT XCal file for <see cref="DefectPixels"/>: the 152-byte header of xcal_format.h (magic, version 1, type DEFECT, UINT8_MASK, 16x16, no expiry, EMPTY session id,
        /// no config, 256-byte payload, SHA-256 of config||payload) and the mask. The module has no generator for defect maps (xpe_bpm_generate yields an in-memory mask).
        /// </summary>
        private static void WriteDefectMapFile(string path)
        {
            var mask = new byte[PixelCount];
            foreach (var i in DefectPixels) mask[i] = 1;

            using var stream = File.Create(path);
            using var w = new BinaryWriter(stream);
            w.Write("XCAL"u8);
            w.Write(1u);                      // version
            w.Write(2u);                      // type: DEFECT
            w.Write(2u);                      // pixel format: UINT8_MASK
            w.Write((uint)Width);
            w.Write((uint)Height);
            w.Write(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
            w.Write(0L);                      // expiry: never
            w.Write(new byte[64]);            // session id
            w.Write(0UL);                     // config length
            w.Write((ulong)mask.Length);      // payload length
            w.Write(SHA256.HashData(mask));   // SHA-256 of (config || payload)
            w.Write(mask);
        }

        private static ushort[] FlatFrame() => Enumerable.Range(0, PixelCount).Select(i => (ushort)(2000 + i % 8 * 100)).ToArray();

        /// <summary>The gain stage's expected output, computed here from the flat frame by arithmetic: input / (flat / mean(flat)), the module's definition of a flat-field gain.</summary>
        private static bool GainStageMatchesExpected(ushort[] offsetOut, float[] gainOut)
        {
            var flat = FlatFrame();
            var mean = flat.Average(v => (double)v);
            for (var i = 0; i < gainOut.Length; i++)
            {
                var expected = offsetOut[i] * mean / flat[i];
                if (Math.Abs(gainOut[i] - expected) > 1e-3 * Math.Max(1.0, Math.Abs(expected)))
                {
                    return false;
                }
            }

            return true;
        }

        private static ushort[] ChainInput()
        {
            var raw = Enumerable.Range(0, PixelCount).Select(index => (ushort)(1000 + index)).ToArray();
            foreach (var i in DefectPixels) raw[i] = HotValue;
            return raw;
        }

        private static ChainRunResult RunChain(Exports e)
        {
            var raw = ChainInput();
            var offsetOut = new ushort[PixelCount];
            var gainOut = new float[PixelCount];
            var defectOut = new float[PixelCount];
            var rawShaBefore = ComputeSha256(raw);
            var stages = new List<PreprocessSyntheticStageResult>();
            var total = Stopwatch.StartNew();

            var offset = Call("offset", e.Offset, raw, offsetOut, XpeCommonApi.XpePixelFormat.UInt16, XpeCommonApi.XpePixelFormat.UInt16);
            var offsetEffect = MaxAbsError(offsetOut, raw);
            stages.Add(offset.ToStageResult(offsetEffect, offset.ErrorCode == XpeCommonApi.XpeErrorCode.OK && offsetEffect > 0));

            var gain = Call("gain", e.Gain, offsetOut, gainOut, XpeCommonApi.XpePixelFormat.UInt16, XpeCommonApi.XpePixelFormat.Float32);
            var gainEffect = MaxAbsError(gainOut, offsetOut);
            stages.Add(gain.ToStageResult(gainEffect, gain.ErrorCode == XpeCommonApi.XpeErrorCode.OK && gainEffect > 0 && GainStageMatchesExpected(offsetOut, gainOut)));

            var defect = Call("defect", e.Defect, gainOut, defectOut, XpeCommonApi.XpePixelFormat.Float32, XpeCommonApi.XpePixelFormat.Float32);
            var defectEffect = MaxAbsError(defectOut, gainOut);
            stages.Add(defect.ToStageResult(defectEffect, defect.ErrorCode == XpeCommonApi.XpeErrorCode.OK && DefectStageCorrectedOnlyTheMarkedPixels(gainOut, defectOut)));
            total.Stop();

            var rawShaAfter = ComputeSha256(raw);
            var nanInfCount = defectOut.Count(value => float.IsNaN(value) || float.IsInfinity(value));
            var inputPreserved = string.Equals(rawShaBefore, rawShaAfter, StringComparison.OrdinalIgnoreCase);
            var passed = inputPreserved && nanInfCount == 0 && defectOut.Max() > 0f && stages.All(stage => stage.Passed);

            return new ChainRunResult(
                Passed: passed,
                TotalLatencyMs: total.Elapsed.TotalMilliseconds,
                InputPreserved: inputPreserved,
                RawSha256Before: rawShaBefore,
                RawSha256After: rawShaAfter,
                NaNInfCount: nanInfCount,
                OutputMin: defectOut.Min(),
                OutputMax: defectOut.Max(),
                Output: defectOut,
                Stages: stages);
        }

        /// <summary>The marked pixels (hot in the input) moved far from the hot value, and every other pixel is bit-identical to the gain stage's output.</summary>
        private static bool DefectStageCorrectedOnlyTheMarkedPixels(float[] before, float[] after)
        {
            for (var i = 0; i < before.Length; i++)
            {
                var marked = DefectPixels.Contains(i);
                var same = BitConverter.SingleToInt32Bits(before[i]) == BitConverter.SingleToInt32Bits(after[i]);
                if (marked ? Math.Abs(after[i] - before[i]) <= HotEffect : !same)
                {
                    return false;
                }
            }

            return true;
        }

        private static TimedCallResult Call<TIn, TOut>(
            string stage,
            CorrectionDelegate correction,
            TIn[] input,
            TOut[] output,
            XpeCommonApi.XpePixelFormat inputFormat,
            XpeCommonApi.XpePixelFormat outputFormat)
            where TIn : struct
            where TOut : struct
        {
            var metadata = new XpeCommonApi.XpeImageMetadata
            {
                BodyPart = "CHEST",
                KVp = 70.0f,
                MAs = 2.0f,
                SID_mm = 1000.0f,
                PixelPitch_mm = 0.14f,
                AcquisitionTime = 0,
                Flags = 0,
            };

            var inPin = GCHandle.Alloc(input, GCHandleType.Pinned);
            var outPin = GCHandle.Alloc(output, GCHandleType.Pinned);
            try
            {
                var inBuffer = MakeBuffer(inputFormat, inPin.AddrOfPinnedObject(), input.Length * Marshal.SizeOf<TIn>());
                var outBuffer = MakeBuffer(outputFormat, outPin.AddrOfPinnedObject(), output.Length * Marshal.SizeOf<TOut>());
                var stopwatch = Stopwatch.StartNew();
                var code = correction(ref inBuffer, ref outBuffer, ref metadata);
                stopwatch.Stop();
                return new TimedCallResult(stage, code, stopwatch.Elapsed.TotalMilliseconds);
            }
            finally
            {
                outPin.Free();
                inPin.Free();
            }
        }

        private static bool TryGetDelegate<TDelegate>(IntPtr handle, string exportName, out TDelegate? value)
            where TDelegate : Delegate
        {
            if (!NativeLibrary.TryGetExport(handle, exportName, out var symbol))
            {
                value = null;
                return false;
            }

            value = Marshal.GetDelegateForFunctionPointer<TDelegate>(symbol);
            return true;
        }

        private static XpeCommonApi.XpeImageBuffer MakeBuffer(XpeCommonApi.XpePixelFormat format, IntPtr data, int dataSize)
        {
            var bits = format switch
            {
                XpeCommonApi.XpePixelFormat.UInt8 => 8u,
                XpeCommonApi.XpePixelFormat.UInt16 => 16u,
                _ => 32u,
            };

            return new XpeCommonApi.XpeImageBuffer
            {
                Width = Width,
                Height = Height,
                BitsAllocated = bits,
                BitsStored = bits,
                Format = format,
                Data = data,
                DataSize = (nuint)dataSize,
            };
        }

        private static double MaxAbsError(ushort[] actual, ushort[] expected)
        {
            var max = 0.0;
            for (var i = 0; i < actual.Length; i++)
            {
                max = Math.Max(max, Math.Abs(actual[i] - expected[i]));
            }

            return max;
        }

        private static double MaxAbsError(float[] actual, ushort[] expected)
        {
            var max = 0.0;
            for (var i = 0; i < actual.Length; i++)
            {
                max = Math.Max(max, Math.Abs(actual[i] - expected[i]));
            }

            return max;
        }

        private static double MaxAbsError(float[] actual, float[] expected)
        {
            var max = 0.0;
            for (var i = 0; i < actual.Length; i++)
            {
                max = Math.Max(max, Math.Abs(actual[i] - expected[i]));
            }

            return max;
        }

        private static double CalculateRmse(float[] first, float[] second)
        {
            var sum = 0.0;
            for (var i = 0; i < first.Length; i++)
            {
                var diff = first[i] - second[i];
                sum += diff * diff;
            }

            return Math.Sqrt(sum / first.Length);
        }

        private static string ComputeSha256<T>(T[] values)
            where T : struct
        {
            var bytes = MemoryMarshal.AsBytes(values.AsSpan());
            return Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
        }

        private sealed record TimedCallResult(
            string Stage,
            XpeCommonApi.XpeErrorCode ErrorCode,
            double LatencyMs)
        {
            public PreprocessSyntheticStageResult ToStageResult(double maxAbsError, bool passed)
            {
                return new PreprocessSyntheticStageResult(Stage, ErrorCode.ToString(), LatencyMs, maxAbsError, passed);
            }
        }

        private sealed record ChainRunResult(
            bool Passed,
            double TotalLatencyMs,
            bool InputPreserved,
            string RawSha256Before,
            string RawSha256After,
            int NaNInfCount,
            double OutputMin,
            double OutputMax,
            float[] Output,
            IReadOnlyList<PreprocessSyntheticStageResult> Stages);
    }
}
