"""Regenerates modules/ai/tests/signer_vectors.inc: signatures made by the INDEPENDENT implementation
(tools/ai/xpe_model_signing.py, Python `cryptography` / OpenSSL) for the C++ verifier (CNG) to accept.

    python modules/ai/tests/data/signing/make_signer_vectors.py

Deterministic: the signatures are RFC 6979, the models are fixed byte patterns, so a rerun rewrites the same file.
The TEST keys test_key_1.pem / test_key_2.pem are committed on purpose; they are not secret and the product never
trusts them. Only public keys and signatures go into the generated file.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "ai"))

import xpe_model_signing as sig  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "signer_vectors.inc")
LARGE = 3 * 1024 * 1024
CHUNK = 64 * 1024 * 1024 + 5   # a few bytes past the verifier's 64 MiB hashing chunk


def pattern(n):
    """The model bytes of the large case: i*31+7 mod 256. The C++ test builds the same bytes from the same formula."""
    return bytes((i * 31 + 7) & 0xFF for i in range(n))


MODEL = bytes((i * 7 + 3) & 0xFF for i in range(768))
SIDECAR = b'{"labels": ["CHEST", "ABDOMEN"]}'

# name, role, model, sidecar (None = absent, b"" = empty), signing key (1 or 2)
CASES = [
    ("bone_with_sidecar", "bone_suppress", MODEL, SIDECAR, 1),
    ("part_no_sidecar", "bodypart", MODEL, None, 1),
    ("part_empty_sidecar", "bodypart", MODEL, b"", 1),
    ("bone_by_key2", "bone_suppress", MODEL, SIDECAR, 2),
    ("large_model", "bone_suppress", LARGE, None, 1),   # an int: the model is pattern(n), built by the test
    ("chunk_model", "bone_suppress", CHUNK, None, 1),
    ("boundary_ab_c", "bone_suppress", b"AB", b"C", 1),
    ("boundary_a_bc", "bone_suppress", b"A", b"BC", 1),
]


def c_array(name, data):
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(data), "\n".join(lines))


def main():
    k1 = sig.load_private_key(os.path.join(HERE, "test_key_1.pem"))
    k2 = sig.load_private_key(os.path.join(HERE, "test_key_2.pem"))
    keys = {1: k1, 2: k2}
    out = ["// GENERATED by modules/ai/tests/data/signing/make_signer_vectors.py -- do not edit by hand.\n",
           "// Signatures by tools/ai/xpe_model_signing.py (Python cryptography / OpenSSL), the independent side of the\n",
           "// format; the C++ verifier (Windows CNG) must accept them. Test keys only: never trusted by the product.\n\n"]
    out.append(c_array("kKey1Xy", sig.public_xy(k1.public_key())))
    out.append(c_array("kKey2Xy", sig.public_xy(k2.public_key())))
    # The TEST key 1 private scalar: public in this repository like the key file it comes from. It lets a C++ test sign a
    # fixture it creates at run time (a temporary model directory with a different sidecar) -- test_signing_helper.h.
    out.append("// Private scalar of TEST key 1 (test_key_1.pem). NOT a secret; the product never trusts this key.\n")
    out.append(c_array("kKey1D", k1.private_numbers().private_value.to_bytes(32, "big")))
    out.append(c_array("kSharedModel", MODEL))
    out.append(c_array("kSharedSidecar", SIDECAR))
    rows = []
    for name, role, model, sidecar, kn in CASES:
        m = pattern(model) if isinstance(model, int) else model
        s = sig.sign(keys[kn], role, m, sidecar)
        assert sig.verify(keys[kn].public_key(), s, role, m, sidecar), name
        out.append(c_array("kSig_%s" % name, s))
        if isinstance(model, int):
            mdl = "nullptr, %d" % model                        # built from the formula
        elif model is MODEL:
            mdl = "kSharedModel, sizeof(kSharedModel)"
        else:
            mdl = '(const uint8_t*)"%s", %d' % (model.decode(), len(model))
        if sidecar is None:
            sc = "false, nullptr, 0"
        elif sidecar is SIDECAR:
            sc = "true, kSharedSidecar, sizeof(kSharedSidecar)"
        elif sidecar == b"":
            sc = "true, nullptr, 0"
        else:
            sc = 'true, (const uint8_t*)"%s", %d' % (sidecar.decode(), len(sidecar))
        rows.append('    {"%s", "%s", %s, %s, kSig_%s},' % (name, role, mdl, sc, name))
    out.append("\nstruct SigCase {\n    const char* name;\n    const char* role;\n    const uint8_t* model;   // nullptr: a formula model of modelSize bytes, ((i * 31 + 7) & 0xFF)\n"
               "    size_t modelSize;\n    bool hasSidecar;\n    const uint8_t* sidecar;\n    size_t sidecarSize;\n    const uint8_t* sig;   // 78 bytes\n};\n")
    out.append("static const SigCase kCases[] = {\n%s\n};\n" % "\n".join(rows))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))
    print("wrote", os.path.relpath(OUT, ROOT), "-", len(CASES), "cases")


if __name__ == "__main__":
    main()
